### ISSUE TITLE
Difference to original implementation

### ISSUE THREAD

**Issue by letmaik** [omarbenhamid/jsdap#1]
I see that this is a fork of https://code.google.com/p/jsdap/

Can you explain which changes/improvements you made and why? I'm interested in using this library.

**Comment by omarbenhamid** [comment]
Hi, 
The difference with with the original implementation is mainly : 
-  The support of NetCDF4 Groups when files are served through OpenDAP
- The ability to add addition HTTP Headers to the request, might be useful for authorisation headers for exemple.
- And some improvement on error messages, documentation, sample html page ...

**Comment by letmaik** [comment]
Just for reference, there is some new development going on at https://bitbucket.org/jetfuse/jsdap
